---

- name: adding user deepak to all nodes
  hosts: web
  become: yes
  gather_facts: no  
  tasks: 
   - name: adding user  now
     user: 
      name: "{{ item }}"
      state: present 
     with_items:
       - vinamra
       - jyotsana
