---
- name: creating multiple files
  hosts: web
  become: yes
  tasks:
   - name: creating five files
     file:
      path: "{{ item }}"
      state: touch
     with_items:
      - text1.txt
      - text2.txt
      - text3.txt
