---
- name: creating webserver
  hosts: web
  become: true
  tasks:
   - name: ensure httpd is present
     yum:
      name: httpd
      state: present

   - name: ensure httpd is started and ensured
     service:
      name: httpd
      state: started
      enabled: true

   - name: copy index.html to /var/www/html
     synchronize: 
      src: index.html
      dest: /var/www/html
