---
# tasks file for apachee
- name: install apache server 
  yum:
   name: httpd
   state: present

- name: check if the httpd is started and enabled
  service: 
   name: httpd
   state: started
   enabled: true

- name: deploy index.html in /var/www
  template:
   src: index.html.j2
   dest: /var/www/html/index.html

